### ISSUE TITLE
Update to CDI 3.0.0M1

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/cditck-porting#15]
Please update CDI TCK Porting kit to Jakarta CDI 3.0.0-M1
http://download.eclipse.org/ee4j/cdi/cdi-tck-3.0.0-M1-dist.zip
(Please double check the folder to be sure a newer version isn't release when you start work)

**Comment by gurunrao** [comment]
The task is dependent on glassfish 6.0 alpha/beta being available for testing with glasshish cdi porting kits. 
Currently glassfish builds are not stable and nightly builds are disabled. The task will be revisited once stable glassfish nightly build for 6.0 is available.

**Comment by edbratt** [comment]
This issue is blocked by https://github.com/eclipse-ee4j/glassfish/issues/23022

**Comment by scottmarlow** [comment]
@gurunrao it looks like we are still testing with CD 2.0 (see https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/55/console).

Also [nightly build via eclipse/downloads is available](https://www.eclipse.org/downloads/download.php?file=/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip).

CC @alwin-joseph @RohitKumarJain

**Comment by gurunrao** [comment]
@scottmarlow - CDI upgrade with glassfish porting kit is WIP, more details can be found with card - https://github.com/eclipse-ee4j/jakartaee-tck/projects/1#card-38069399

**Comment by gurunrao** [comment]
Latest CI run has all tests pass. CI run can be found here - https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/72/testReport/
