### ISSUE TITLE
support CDI TCK 4.1.0 with latest Glassfish build.

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/cditck-porting#29]
support CDI TCK 4.0.0 with latest Glassfish build.
CDI TCK[ https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/enterprise/cdi-tck-dist/ ] with latest Glassfish build.

**Comment by arjantijms** [comment]
Just a note: GF master is in progress of switching over to GF 7/EE10/CDI 4.
